os: Visual Studio 2017
version: 1.0.0.{build}
platform:
- Any CPU
skip_branch_with_pr: true
configuration:
- Release
build_script:
  - dotnet publish -c %CONFIGURATION%
after_build:
- cmd: >-
    cd bin/Release/netcoreapp2.0/publish

    7z a AntlrGen-%APPVEYOR_BUILD_VERSION%.zip *.dll *.json *.jar
artifacts:
- path: bin/$(configuration)/netcoreapp2.0/publish/*.zip
  name: AntlrGen